version: '3.1'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      TZ: Asia/Shanghai
    volumes:
      - ./data/mysql/db:/var/lib/mysql
      - ./data/mysql/conf:/etc/mysql/conf.d
      - ./data/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  redis:
    image: redis:latest
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data/redis/redis.conf:/etc/redis.conf
      - ./data/redis/data:/data/
    ports:
      - 6379:6379

  mochat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9501:9501
    depends_on:
      - mysql
      - redis