spring:
  datasource:
    url: jdbc:mysql://mysql:3306/mochat?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&autoReconnect=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    filters: stat,wall
  devtools:
    restart:
      #热部署生效
      enabled: true
  redis:
    host: redis
    port: 6379
    password:
    timeout: 5000
    database: 1

#OSS
oss:
  endpoint: xxxx
  accessKeyId: xxxx
  accessKeySecret: xxxx
  bucketName: xxxx
